### ISSUE TITLE
Unreferenced utility, ng.pl

### ISSUE THREAD

**Issue by ralmond** [eddelbuettel/ppa-rstudio#1]
Thanks for making this available.  The first part of the script runs great.  However, it fails at line 32 with a reference to `~/bin/ng.pl`; which I'm guessing signs the package.

Can you share that script or point to where to get it?

**Comment by eddelbuettel** [comment]
I cannot, it is a local script.  Sorry.  

You can comment it out to leave the file unsigned, or find another tool to sign a (text) file like packages.
